// Manually copied from Full Framework project

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetStandard.Whois {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webservicex.net", ConfigurationName="Whois.whoisSoap")]
    public interface whoisSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/GetWhoIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetWhoIS(string HostName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webservicex.net/GetWhoIS", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetWhoISAsync(string HostName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface whoisSoapChannel : DotNetStandard.Whois.whoisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class whoisSoapClient : System.ServiceModel.ClientBase<DotNetStandard.Whois.whoisSoap>, DotNetStandard.Whois.whoisSoap {
        
        public whoisSoapClient() {
        }
        
        public whoisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public whoisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public whoisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public whoisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWhoIS(string HostName) {
            return base.Channel.GetWhoIS(HostName);
        }
        
        public System.Threading.Tasks.Task<string> GetWhoISAsync(string HostName) {
            return base.Channel.GetWhoISAsync(HostName);
        }
    }
}
